Wordless/Wordless/Controllers/AuthorPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wordless.Models;
using System.Data.Entity;
using Wordless.ViewModel;

namespace Wordless.Controllers
{
    public class AuthorPageController : Controller
    {
        WordlessContext db = new WordlessContext();
        
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Index()
        {
            SetListsForViews();
            Book book = new Book();
            AuthorPageViewModel author = new AuthorPageViewModel();

            //ViewBag.List = author.BooksResult.ToList();

            author.BooksResult = book.GetAll();
            
            return View(author);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Index(AuthorPageViewModel author)
        {
            SetListsForViews();
            if (ModelState.IsValid)
            {
                Book book = new Book();

                var books = book.GetAll();
               
                if (!String.IsNullOrEmpty(author.Keyword))
                {
                    books = books.Where(b => b.Title.ToLower().Contains(author.Keyword.ToLower())).ToList();
                }
                author.BooksResult = books;
            }
            return View(author);
        }

        public ActionResult Details(int id)
        {
            Book book = db.Books.Single(b => b.BookId == id);
            
            return View(book);
        }

        [HttpGet]
        public ActionResult Create()
        {
            SetListsForViews();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book, HttpPostedFileBase upload)
        {
            SetListsForViews();
            if (ModelState.IsValid)
            {
                var userId = (Int64)Session["currentUserId"];
                var user = db.Users.Find(userId);
                var newFile = new File
                {
                    FileName = System.IO.Path.GetFileName(upload.FileName),
                    ContentType = upload.ContentType,
                    User = user,
                    UploadedOn = DateTime.Now

                };
                if (newFile.ContentType == "application/pdf")
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        newFile.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    db.Files.Add(newFile);
                }
                
                book.File = newFile;
                book.Author = user;
                db.Books.Add(book);   
                db.SaveChanges();
                return Redirect("Create");               
            }
            return View(book);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Book book = db.Books.Single(b => b.BookId == id);

            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                Book bookFromDB = db.Books.Single(b => b.BookId == book.BookId);

                bookFromDB.Title = book.Title;
                bookFromDB.TimesPurchased = book.TimesPurchased;
                bookFromDB.Genre = book.Genre;
                bookFromDB.Price = book.Price;
                bookFromDB.Comments = book.Comments;

                db.SaveChanges();

                return RedirectToAction("Details", new { id = book.BookId });
            }
            return View(book);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Book book = db.Books.Single(b => b.BookId == id);

            if (book == null)
            {
                return HttpNotFound();
            }
            
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Book book = db.Books.Single(b => b.BookId == id);
            db.Books.Remove(book);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public void SetListsForViews()
        {
            WordlessContext db = new WordlessContext();
            //sparar mest nedladdade i en lista
            ViewBag.MostDownloaded = (from d in db.Books
                                      orderby d.TimesPurchased descending
                                      select d).Take(4).ToList();
            var listFromDb = db.PurchasedBooks.Include(u => u.Buyer).ToList();
            List<PurchasedBook> purchasedList = new List<PurchasedBook>();
            //räknar ut snittet på rating
            foreach (var item in listFromDb)
            {
                //hur många gånger en bok har blvit köpt
                var times = db.PurchasedBooks.Where(t => t.BookId == item.BookId).Count();
                if (times > 1 && purchasedList.Any(f => f.BookId == item.BookId) == false)
                {
                    //totala summan av alla ratings
                    var sum = db.PurchasedBooks.Where(t => t.BookId == item.BookId).Sum(t => t.Rating);
                    //summan delat på antalet nedladdingar(förutsatt att alla har gett en rating :) ) 
                    var avgRating = sum / times;
                    item.Rating = avgRating;
                }
                if (purchasedList.Any(f => f.BookId == item.BookId) == false)
                {
                    purchasedList.Add(item);
                }
                //sorterar listan
                var sortedList = (from x in purchasedList
                                  orderby x.Rating descending
                                  select x).Take(4).ToList();
                ViewBag.BestRating = sortedList;
                //skapar en lista av antalet kommentarer
                ViewBag.MostCommented = (from b in db.Books
                                         orderby b.Comments.Count() descending
                                         select b).Take(4).ToList();
            }
        }
    }
}

Wordless/Wordless/Views/AuthorPage/Delete.cshtml
@model Wordless.Models.Book

@{
    ViewBag.Title = "Delete";
}


<div class="container">
    <div class="bodyDiv register-page-div">
        <div>
            <h2>Delete</h2>

            <h3>Are you sure you want to delete this?</h3>
            <h4>Book</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TimesPurchased)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TimesPurchased)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Genre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Genre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    
                </div>
            }
        </div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Wordless/Wordless/Views/AuthorPage/Details.cshtml
@model Wordless.Models.Book

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <div class="bodyDiv register-page-div">
        <div>
            <h2>Details</h2>

            @Html.DisplayForModel()

            @Html.ActionLink("Back to Book List", "Index", "AuthorPage")

        </div>
    </div>
</div>

Wordless/Wordless/Views/AuthorPage/Edit.cshtml
@model Wordless.Models.Book

@{
    ViewBag.Title = "Edit";
}




<div class="container">
    <div class="bodyDiv register-page-div">
        <div class="form-horizontal row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <h4>Book</h4>
                <hr />
                <form role="form" action="~/AuthorPage/Edit" method="post">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.BookId)

                    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.Title)
                        @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TimesPurchased)
                        @Html.EditorFor(m => m.TimesPurchased, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.Genre)
                        @Html.EnumDropDownListFor(m => m.Genre, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.Price)
                        @Html.EditorFor(m => m.Price, new { htmlAttributes = new { @class = "form-control" } })
                    </div>

                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                    
                </form>
                
            </div>
        </div>
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>

Wordless/Wordless/Views/AuthorPage/Index.cshtml
@model Wordless.ViewModel.AuthorPageViewModel
@using Wordless.ViewModel
@using Wordless.Models

@{
    ViewBag.Title = "Index";
}   


<div class="container">
    <div class="bodyDiv register-page-div">
        <div class="form-horizontal row">
            <p style="margin-left:20px;">@Html.ActionLink("Create", "Create", "AuthorPage")</p>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <h2>Filter</h2>
                <form role="form" action="~/AuthorPage/Index" method="post">
                    @Html.AntiForgeryToken()
                    <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.Keyword)
                        @Html.TextBoxFor(m => m.Keyword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Keyword)
                    </div>
                    <div class="form-group col-md-offset-2 col-md-10">
                        <input type="submit" value="Filter" class="btn btn-default" />
                    </div>
                    <
                </form>

            </div>


            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                @{
                    if (Model.BooksResult.Count() > 0)
                    {
                        <h2>Found <strong>@Model.BooksResult.Count()</strong> properties</h2>
                        @Html.Raw("<div class = 'books'>");
                foreach (Book b in Model.BooksResult)
                {
                            @Html.Raw("<div>");
                            @Html.Raw("<strong>" + b.Title + "</strong><br />");
                            @Html.Raw("TimesPurchased: " + b.TimesPurchased + "<br />");
                            @Html.Raw("Price: &#36;" + b.Price + "<br />");
                            @Html.ActionLink("Edit", "Edit", new { id = b.BookId })
                            @Html.Raw("<br />")
                            @Html.ActionLink("Details", "Details", new { id = b.BookId })
                            @Html.Raw("<br />")
                            @Html.ActionLink("Delete", "Delete", new { id = b.BookId })
                            @Html.Raw("</div>")
                            @Html.Raw("<br />")
                        }
                        @Html.Raw("</div>")
                    }

                    else
                    {
                        <h2>Sorry!</h2>
                        <p>No books could be found =(</p>
                    }
                }
            </div>

        </div>
    </div>
</div>