Wordless/Wordless/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using Wordless.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Wordless.Controllers
{
    public class FileController : Controller
    {
        WordlessContext db = new WordlessContext();        
        public List<PurchasedBook> CreateFileList()
        {
            //en lista på vilka filer en användare har laddat upp
            var userId = (Int64)Session["currentUserId"];
            var purchasedBookList = (from l in db.PurchasedBooks
                        where l.BuyerId == userId
                        select l).ToList();
            return purchasedBookList;
        }
        //var bookList = db.PurchasedBooks.Include(b => b.Book).ToList();
        //List<Book> bookList = db.Books.Include(b => b.Author).Include(c => c.Comments).ToList();
        public ActionResult UploadPDF()
        {
            return View();
        }
        public ActionResult ReadPDF()
        {
            SetListsForViews();
            return View(CreateFileList());
        }
        public ActionResult ChangeFile(int fileId)
        {
            //ändrar vilken fil som ska visas i browsern som ett sessions-objekt
            Session["pdfIdToShow"] = fileId;
            return RedirectToAction("ReadPDF");
        }
        public ActionResult ShowFile()
        {
            {
                //visa filen i browsern från sessions-objektet
                var fileToGet = db.Files.Find(Session["pdfIdToShow"]);
                if (fileToGet == null)
                {
                    return null;
                }
                return File(fileToGet.Content, fileToGet.ContentType);
            }
        }
        //när man ska se PDF:en i helskärm
        public ActionResult GetFile(int fileId)
        {
            if (fileId == 0)
            {
                return View("Index");
            }
            else
            {
                var fileToGet = db.Files.Find(fileId);
                return File(fileToGet.Content, fileToGet.ContentType);
            }
        }
        //när man vill ladda hem PDF:en
        public ActionResult DownloadFIle(int fileId)
        {
            if (fileId == 0)
            {
                return View("Index");
            }
            else
            {
                var fileToGet = db.Files.Find(fileId);
                return File(fileToGet.Content, fileToGet.ContentType, fileToGet.FileName);
            }
        }
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase upload)
        {
            if (upload == null)
            {
                return View("Index");
            }
            else
            {
                // hämtar userid och användare
                var userId = (Int64)Session["currentUserId"];
                var user = db.Users.Find(userId);
                //skapa ny fil
                var newFile = new File
                {
                    FileName = System.IO.Path.GetFileName(upload.FileName),
                    ContentType = upload.ContentType,
                    User = user,
                    UploadedOn = DateTime.Now
                    
                };
                if (newFile.ContentType == "application/pdf")
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        newFile.Content = reader.ReadBytes(upload.ContentLength);
                    }        
                    db.Files.Add(newFile);

                    Book book = new Book
                    {
                        Title = "Mästerdetektiven Blomkvist",
                        TimesPurchased = 10,
                        BookText = "Det är sommarlov och de tre 13-åriga kompisarna Kalle, Anders och Eva-Lotta har det lite småtråkigt.",
                        Price = 20,
                        Author = user,
                        Genre = Genres.Crime,
                        File = newFile
                    };
                    db.Books.Add(book);


                    db.SaveChanges();




                    return Redirect("/AuthorPage/Create");
                }
                else
                {
                    return View("Index", CreateFileList());
                }
            }
        }
        public ActionResult PDFPartialView()
        {
            return PartialView();
        }
        public void SetListsForViews()
        {
            WordlessContext db = new WordlessContext();
            //sparar mest nedladdade i en lista
            ViewBag.MostDownloaded = (from d in db.Books
                                      orderby d.TimesPurchased descending
                                      select d).Take(4).ToList();
            var listFromDb = db.PurchasedBooks.Include(u => u.Buyer).ToList();
            List<PurchasedBook> purchasedList = new List<PurchasedBook>();
            //räknar ut snittet på rating
            foreach (var item in listFromDb)
            {
                //hur många gånger en bok har blvit köpt
                var times = db.PurchasedBooks.Where(t => t.BookId == item.BookId).Count();
                if (times > 1 && purchasedList.Any(f => f.BookId == item.BookId) == false)
                {
                    //totala summan av alla ratings
                    var sum = db.PurchasedBooks.Where(t => t.BookId == item.BookId).Sum(t => t.Rating);
                    //summan delat på antalet nedladdingar(förutsatt att alla har gett en rating :) ) 
                    var avgRating = sum / times;
                    item.Rating = avgRating;
                }
                if (purchasedList.Any(f => f.BookId == item.BookId) == false)
                {
                    purchasedList.Add(item);
                }
                //sorterar listan
                var sortedList = (from x in purchasedList
                                  orderby x.Rating descending
                                  select x).Take(4).ToList();
                ViewBag.BestRating = sortedList;
                //skapar en lista av antalet kommentarer
                ViewBag.MostCommented = (from b in db.Books
                                         orderby b.Comments.Count() descending
                                         select b).Take(4).ToList();
            }
        }
    }
}

Wordless/Wordless/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wordless.Models;
using System.Data.Entity;

namespace Wordless.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Register()
        {
            WordlessContext db = new WordlessContext();
            SetListsForViews();
            string name = Request["name"];
            string username = Request["username"];
            string password = Request["password"];
            string email = Request["email"];
            bool author = false;

            if (Request["isAuthor"] != null)
            {
                author = bool.Parse(Request["isAuthor"]);
            }
            if (name == null || username == null || password == null || email == null)
            {
                TempData["error"] = "";
                return View();
            }       

            if (db.Users.Where(n => n.Username.ToLower() == username.ToLower()).Count() == 0)
            {
                User user = new User { Name = name, Username = username, Password = password, Email = email, Author = author };
                db.Users.Add(user);
                db.SaveChanges();
                TempData["error"] = "Registered successfully";
                return View();
            }

            else if (db.Users.Where(u => u.Username == username).Count() > 0 || db.Users.Where(e => e.Email == email).Count() > 0)
            {
                TempData["error"] = "User already exists";
                return View();
            }

            else
            {
                return View();
            }
        }

        public ActionResult Login()
        {
            try
            {
                WordlessContext db = new WordlessContext();
                string username = Request["username"];
                string password = Request["password"];
                var userList = db.Users.Where(u => u.Username.ToLower() == username.ToLower()).ToList();
                if (userList.Count() == 1 && userList.First().Password == password)
                {
                    ///Set session values
                    Session["currentUserId"] = userList.First().UserId;
                    Session["currentUsername"] = userList.First().Username;
                    Session["loginStatus"] = true;

                    if (username.ToLower() == "patrik")
                    {
                        Session["Admin"] = true;
                    }
                    else if (userList.Where(u => u.Username == username).First().Author)
                    {
                        Session["isAuthor"] = true;
                    }

                    TempData["error"] = "Welcome " + Session["currentUsername"];
                    return Redirect("/Home/Index");
                }
                else
                {
                    TempData["error"] = "Check username and/or password";
                    return RedirectToAction("Register"); // Redirect("/Default/Login");
                }
            }
            catch
            {
                ///Return to login/register -view to try again
                TempData["error"] = "Database fail!";
                return View("Register"); // Redirect("/Default/Login");           
            }
        }
        public ActionResult Logout()
        {
            ///reset session values
            Session["currentUserId"] = 0;
            Session["currentUsername"] = "";
            Session["currentUserLastName"] = "";
            Session["loginStatus"] = false;
            Session["Admin"] = false;
            Session["isAuthor"] = false;

            return RedirectToAction("Register"); //Go back to register view on succesful logout
        }
        public ActionResult UserHome()
        {
            if ((bool)Session["loginStatus"])
            {
                ViewBag.Message = "Welcome " + Session["currentUsername"];
                var userId = Convert.ToDouble(Session["currentUserId"]);
                WordlessContext db = new WordlessContext();
                var userInfo = (db.Users
                    .Include(b => b.WrittenBooks)
                    .Include(c => c.Comments)
                    .Include(p => p.PurchasedBooks)
                    .Where(u => u.UserId == userId)).SingleOrDefault();
                return View(userInfo);
            }
            else
            {
                return Redirect("/user/Register");
            }

        }

        public ActionResult RegisterLogin()
        {
            return View();
        }
        public void SetListsForViews()
        {
            WordlessContext db = new WordlessContext();
            //sparar mest nedladdade i en lista
            ViewBag.MostDownloaded = (from d in db.Books
                                      orderby d.TimesPurchased descending
                                      select d).Take(4).ToList();
            var listFromDb = db.PurchasedBooks.Include(u => u.Buyer).ToList();
            List<PurchasedBook> purchasedList = new List<PurchasedBook>();
            //räknar ut snittet på rating
            foreach (var item in listFromDb)
            {
                //hur många gånger en bok har blvit köpt
                var times = db.PurchasedBooks.Where(t => t.BookId == item.BookId).Count();
                if (times > 1 && purchasedList.Any(f => f.BookId == item.BookId) == false)
                {
                    //totala summan av alla ratings
                    var sum = db.PurchasedBooks.Where(t => t.BookId == item.BookId).Sum(t => t.Rating);
                    //summan delat på antalet nedladdingar(förutsatt att alla har gett en rating :) ) 
                    var avgRating = sum / times;
                    item.Rating = avgRating;
                }
                if (purchasedList.Any(f => f.BookId == item.BookId) == false)
                {
                    purchasedList.Add(item);
                }
                //sorterar listan
                var sortedList = (from x in purchasedList
                                  orderby x.Rating descending
                                  select x).Take(4).ToList();
                ViewBag.BestRating = sortedList;
                //skapar en lista av antalet kommentarer
                ViewBag.MostCommented = (from b in db.Books
                                         orderby b.Comments.Count() descending
                                         select b).Take(4).ToList();
            }
        }
    }
}

Wordless/Wordless/Controllers/UserPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wordless.Models;
using Wordless.ViewModel;

namespace Wordless.Controllers
{
    public class UserPageController : Controller
    {
        WordlessContext db = new WordlessContext();

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Index()
        {
            PurchasedBook PurchasedBook = new PurchasedBook();
            PurchasedBookViewModel PurchasedBookViewModel = new PurchasedBookViewModel();
            

            PurchasedBookViewModel.PurchasedBookResult = PurchasedBook.GetAll();

            return View(PurchasedBookViewModel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Index(PurchasedBookViewModel PurchasedBookViewModel)
        {
            if (ModelState.IsValid)
            {
                PurchasedBook PurchasedBook = new PurchasedBook();

                var books = PurchasedBook.GetAll();
                
                if (!String.IsNullOrEmpty(PurchasedBookViewModel.Keyword))
                {
                    books = books.Where(b => b.Book.Title.ToLower().Contains(PurchasedBookViewModel.Keyword.ToLower())).ToList();
                }
                PurchasedBookViewModel.PurchasedBookResult = books;
            }
            return View(PurchasedBookViewModel);
        }

        public ActionResult Details(int id)
        {
            Book book = db.Books.Single(b => b.BookId == id);

            return View(book);
        }
         
        public ActionResult RemoveBook(int id)
        {
            if (ModelState.IsValid)
            {
                PurchasedBook book = db.PurchasedBooks.Single(b => b.PurchasedBookId == id);
                db.PurchasedBooks.Remove(book);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }
    }
}

Wordless/Wordless/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    bool IsAdmin = Session["Admin"] == null ? false : (bool)Session["Admin"];
    bool isAuthor = Session["isAuthor"] == null ? false : (bool)Session["isAuthor"];
    bool loginStatus = Session["loginStatus"] == null ? false : (bool)Session["loginStatus"];
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wordless</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <!--Login stylesheet-->
    <link href="~/Content/login.css" type="text/css" rel="stylesheet"/>
    <!--Facebook Api script-->
    <script type="text/javascript" src="~/Scripts/FacebookLogin.js"></script>

</head>
<body id="LayoutBody">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="~/Home/Index"> <img style="margin-left:30px; margin-right:3px; border-radius:5px;" src="~/Img/minibanner.jpg" /></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse max-width-navbar" id="navbar-collapse">
                <button class="btn dropbtn" href="/Home/Index" type="button" onclick="location.href='@Url.Action("Index", "Home")'">
                    Home
                </button>
                <button class="btn dropbtn top" type="button" onclick="location.href='@Url.Action("Index", "Book")'">Books</button>
                <button class="btn dropbtn top" href="/Home/Index" type="button" onclick="location.href='@Url.Action("ReadPDF", "File")'">
                    Read books
                </button>
                <div class="dropdown">
                    <button class="btn dropbtn dropdown-toggle hidden-sm hidden-xs" href="/Book/Index" type="button" data-toggle="dropdown">
                        Books by genre
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Thriller", "BookByGenre", "Book", new { id = 0 }, new object { })</li>
                        <li>@Html.ActionLink("Romance", "BookByGenre", "Book", new { id = 1 }, new object { })</li>
                        <li>@Html.ActionLink("ScienceFiction", "BookByGenre", "Book", new { id = 2 }, new object { })</li>
                        <li>@Html.ActionLink("Fantasy", "BookByGenre", "Book", new { id = 3 }, new object { })</li>
                        <li>@Html.ActionLink("Travel", "BookByGenre", "Book", new { id = 4 }, new object { })</li>
                        <li>@Html.ActionLink("Mystery", "BookByGenre", "Book", new { id = 5 }, new object { })</li>
                        <li>@Html.ActionLink("Philosophy", "BookByGenre", "Book", new { id = 6 }, new object { })</li>
                        <li>@Html.ActionLink("Religion", "BookByGenre", "Book", new { id = 7 }, new object { })</li>
                        <li>@Html.ActionLink("Crime", "BookByGenre", "Book", new { id = 8 }, new object { })</li>
                        <li>@Html.ActionLink("History", "BookByGenre", "Book", new { id = 9 }, new object { })</li>
                    </ul>
                    
                </div>
                
                <div class="nav navbar-nav navbar-right">

                    @{
                        if ((bool)Session["loginStatus"] && (bool)Session["Admin"])
                        {

                            @*@Html.ActionLink("Admin", "Index", "Admin")*@
                            <button class="btn dropbtn login-logout-button" type="button" onclick="location.href='@Url.Action("Create", "AuthorPage")'">
                                Upload book
                            </button>
                            <button class="btn dropbtn" type="button" onclick="location.href='@Url.Action("Index", "Admin")'">
                                Admin
                            </button>
                            <button class="btn dropbtn" type="button" onclick="location.href='@Url.Action("Logout", "User")'">
                                Logout
                            </button>
                           
                        }

                        else if ((bool)Session["loginStatus"] && (bool)Session["isAuthor"])
                        {
                            @*@Html.ActionLink("Author page", "Index", "AuthorPage")*@
                            <button class="btn dropbtn login-logout-button" type="button" onclick="location.href='@Url.Action("Create", "AuthorPage")'">
                                Upload book
                            </button>
                            <button class="btn dropbtn" type="button" onclick="location.href='@Url.Action("Index", "AuthorPage")'">
                                Author page
                            </button>
                            <button class="btn dropbtn" type="button" onclick="location.href='@Url.Action("Logout", "User")'">
                                Logout
                            </button>
                        }

                        else if ( Session["Admin"]!=null&&(bool)Session["loginStatus"] && (bool)Session["isAuthor"] == false && (bool)Session["Admin"] == false)
                        {
                            @*@Html.ActionLink("My page", "Index", "UserPage")*@
                            <button style="margin-left:18px;" class="btn dropbtn" type="button" onclick="location.href='@Url.Action("Index", "UserPage")'">
                                My page
                            </button>
                            <button class="btn dropbtn" type="button" onclick="location.href='@Url.Action("Logout", "User")'">
                                Logout
                            </button>
                        }

                    }


                    @if (Session["loginStatus"]!=null&&!(bool)Session["loginStatus"])
                    {

                        <button class="btn dropbtn login-logout-button" type="button" onclick="location.href='@Url.Action("Register", "User")'">
                            Login
                        </button>
                    }                    

                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; WORDLESS @DateTime.Now</p>
            <div id="fb-root"></div>
            <div class="fb-like" data-href="https://www.facebook.com/WordlesECStudenter/" data-layout="standard" 
                 data-action="like" data-show-faces="true" data-share="true"></div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/ChristianJavascript.js"></script>
    <script src="~/Scripts/rating.js"></script>
    <!--LOGIN JQUERY-->
    <script src="~/Scripts/login.js"></script>

</body>

</html>